name: GHA_THREE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a test script
        run: echo "This is run on ${RUNNER_OS}"

      - name: 'Test variable name run: echo The value of the variable is: ${{ vars.JOB_NAME }}'
        run: echo 'The value of the variable is: ${{ vars.JOB_NAME }}'