name: GHA_THREE

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
          OPP_SYS: ${RUNNER_OS}
    steps:
      - uses: actions/checkout@v3

      - name: Run a test script
        run: echo "This is run on ${RUNNER_OS}"

      - name: Display the JOB_NAME variable
        run: echo "The JOB_NAME variable value is ${{ vars.JOB_NAME }}"

      - name: Display the env variable using env
        run: echo "The env variable value is ${{ env.OPP_SYS }}"
        
